import { Produto } from "@/types";

export const produtos: Produto[] = [
  {
    id: "1",
    nome: "Pacote de Pedrinhas Nutritivas",
    categoria: "Alimentação",
    preco: 19.9,
    descricao: "Petiscos minerais ricos em cálcio para seu pet rock crescer forte.",
    emoji: "🪨",
    emEstoque: true,
  },
  {
    id: "2",
    nome: "Shampoo Brilho Rochoso 250ml",
    categoria: "Higiene",
    preco: 34.5,
    descricao: "Deixa a superfície do seu pet rock com brilho intenso e proteção anti-poeira.",
    emoji: "🧴",
    emEstoque: true,
  },
  {
    id: "3",
    nome: "Guitarra de Brinquedo Squeak",
    categoria: "Brinquedos",
    preco: 59.9,
    descricao: "Guitarra macia que range ao apertar — diversão garantida para seu rockeiro.",
    emoji: "🎸",
    emEstoque: true,
  },
  {
    id: "4",
    nome: "Jaqueta de Couro Rocker (PP)",
    categoria: "Acessórios",
    preco: 89.9,
    descricao: "Jaqueta de couro sintético com spikes nos ombros. Tamanho pet rock.",
    emoji: "👕",
    emEstoque: true,
  },
  {
    id: "5",
    nome: "Suplemento Mineral Premium",
    categoria: "Alimentação",
    preco: 49.9,
    descricao: "Complexo vitamínico mineral para pet rocks exigentes. 30 cápsulas.",
    emoji: "💎",
    emEstoque: true,
  },
  {
    id: "6",
    nome: "Osso Microfone Cantor",
    categoria: "Brinquedos",
    preco: 44.9,
    descricao: "Osso em formato de microfone para o rockstar dentro do seu pet.",
    emoji: "🎤",
    emEstoque: false,
  },
  {
    id: "7",
    nome: "Coleira Spike Preto",
    categoria: "Acessórios",
    preco: 69.9,
    descricao: "Coleira ajustável com spikes metálicos. Estilo punk rock.",
    emoji: "⛓️",
    emEstoque: true,
  },
  {
    id: "8",
    nome: "Óculos Escuros Rock Star",
    categoria: "Acessórios",
    preco: 99.9,
    descricao: "Óculos escuros estilo aviador para seu pet arrasar no visual.",
    emoji: "🕶️",
    emEstoque: true,
  },
];
