import { Produto } from "@/types";

export const produtos: Produto[] = [
  {
    id: "1",
    nome: "Pacote de Pedrinhas Nutritivas",
    categoria: "Alimentação",
    preco: 19.9,
    descricao: "Petiscos minerais ricos em cálcio para seu pet rock crescer forte.",
    emoji: "🪨",
    emEstoque: true,
  },
  {
    id: "2",
    nome: "Shampoo Brilho Rochoso 250ml",
    categoria: "Higiene",
    preco: 34.5,
    descricao: "Deixa a superfície do seu pet rock com brilho intenso e proteção anti-poeira.",
    emoji: "🧴",
    emEstoque: true,
  },
  {
    id: "3",
    nome: "Guitarra de Brinquedo Squeak",
    categoria: "Brinquedos",
    preco: 59.9,
    descricao: "Guitarra macia que range ao apertar — diversão garantida para seu rockeiro.",
    emoji: "🎸",
    emEstoque: true,
  },
  {
    id: "4",
    nome: "Jaqueta de Couro Rocker (PP)",
    categoria: "Acessórios",
    preco: 89.9,
    descricao: "Jaqueta de couro sintético com spikes nos ombros. Tamanho pet rock.",
    emoji: "👕",
    emEstoque: true,
  },
  {
    id: "5",
    nome: "Suplemento Mineral Premium",
    categoria: "Alimentação",
    preco: 49.9,
    descricao: "Complexo vitamínico mineral para pet rocks exigentes. 30 cápsulas.",
    emoji: "💎",
    emEstoque: true,
  },
  {
    id: "6",
    nome: "Osso Microfone Cantor",
    categoria: "Brinquedos",
    preco: 44.9,
    descricao: "Osso em formato de microfone para o rockstar dentro do seu pet.",
    emoji: "🎤",
    emEstoque: false,
  },
  {
    id: "7",
    nome: "Coleira Spike Preto",
    categoria: "Acessórios",
    preco: 69.9,
    descricao: "Coleira ajustável com spikes metálicos. Estilo punk rock.",
    emoji: "⛓️",
    emEstoque: true,
  },
  {
    id: "8",
    nome: "Óculos Escuros Rock Star",
    categoria: "Acessórios",
    preco: 99.9,
    descricao: "Óculos escuros estilo aviador para seu pet arrasar no visual.",
    emoji: "🕶️",
    emEstoque: true,
  },
  {
    id: "9",
    nome: "Ração Energética Power Rock",
    categoria: "Alimentação",
    preco: 39.9,
    descricao: "Ração premium com minerais essenciais para o dia a dia do seu pet rock.",
    emoji: "🍖",
    emEstoque: true,
  },
  {
    id: "10",
    nome: "Petisco Cálcio + Ferro",
    categoria: "Alimentação",
    preco: 14.9,
    descricao: "Petisco fortificado para pet rocks que precisam de nutrição extra.",
    emoji: "🦴",
    emEstoque: true,
  },
  {
    id: "11",
    nome: "Toalha Umedecida Pet Rock",
    categoria: "Higiene",
    preco: 22.9,
    descricao: "Pacote com 30 unidades para limpeza rápida do seu pet rock.",
    emoji: "🧻",
    emEstoque: true,
  },
  {
    id: "12",
    nome: "Cera Protetora Brilho Total",
    categoria: "Higiene",
    preco: 44.9,
    descricao: "Cera enceradeira que protege e dá brilho extra ao seu pet rock.",
    emoji: "✨",
    emEstoque: true,
  },
  {
    id: "13",
    nome: "Bola de Futebol Rockeiro",
    categoria: "Brinquedos",
    preco: 39.9,
    descricao: "Bola leve para o seu pet rock rolar e se divertir como um campeão.",
    emoji: "⚽",
    emEstoque: true,
  },
  {
    id: "14",
    nome: "Bateria Eletrônica Pet Rock",
    categoria: "Brinquedos",
    preco: 74.9,
    descricao: "Mini bateria com sons de rock para o músico dentro do seu pet.",
    emoji: "🥁",
    emEstoque: true,
  },
  {
    id: "15",
    nome: "Bandana Vermelha Rocker",
    categoria: "Acessórios",
    preco: 29.9,
    descricao: "Bandana vermelha de bandana para seu pet rock virar um astro do rock.",
    emoji: "🧣",
    emEstoque: true,
  },
  {
    id: "16",
    nome: "Pulseira de Spike Metal",
    categoria: "Acessórios",
    preco: 49.9,
    descricao: "Pulseira ajustável com spikes de metal para o visual punk rock.",
    emoji: "📿",
    emEstoque: true,
  },
];
